#!/bin/bash

COIN_NAME='ZELCASH' #no spaces

#wallet information
WALLET_DOWNLOAD='https://zelcore.io/downloads/nodes/testnetv6/zelcash-binaries.tar.gz'
WALLET_TAR_FILE='zelcash-binaries.tar.gz'
ZIPTAR='unzip' #can be either unzip or tar -xvzf
EXTRACT_DIR='' #not always necessary, can be blank if zip/tar file has no subdirectories
CONFIG_FILE='zelcash.conf'
RPCPORT=26124
PORT=26125
COIN_DAEMON='zelcashd'
COIN_CLI='zelcash-cli'
#COIN_TX='zelcash-tx'
COIN_PATH='/usr/local/bin'
USERNAME=$(whiptail --inputbox "Enter su username" 10 30 3>&1 1>&2 2>&3)

YELLOW='\033[1;33m'
BLUE='\033[1;34m'
GREEN='\033[1;32m'
CYAN='\033[1;36m'
NC='\033[0m'
PURPLE='\e[35m'
STOP='\e[0m'

FETCHPARAMS='https://raw.githubusercontent.com/zelcash/zelcash/master/zcutil/fetch-params.sh'

#end of required details
#
#
#

echo -e "${YELLOW}=================================================================="
echo "INSTALLING ZELNODE DEPENDENCIES"
echo -e "==================================================================${NC}"
echo "Installing packages and updates..."
sudo apt-get update -y
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:bitcoin/bitcoin -y
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install git -y
sudo apt-get install curl -y
sudo apt-get install nano -y
sudo apt-get install pwgen -y
sudo apt-get install ufw -y
sudo apt-get install dnsutils -y
sudo apt-get install build-essential libtool autotools-dev pkg-config libssl-dev -y
sudo apt-get install libc6-dev m4 g++-multilib -y
sudo apt-get install autoconf libtool ncurses-dev unzip git python python-zmq -y
sudo apt-get install zlib1g-dev wget curl bsdmainutils automake -y
sudo apt-get install libboost-all-dev -y
sudo apt-get install libevent-dev -y
sudo apt-get install libminiupnpc-dev -y
sudo apt-get install libzmq3-dev -y
sudo apt-get install autoconf -y
sudo apt-get install automake -y
sudo apt-get install unzip -y
sudo apt-get install figlet toilet -y
sudo apt-get install libdb4.8-dev libdb4.8++-dev -y
sudo apt-get install libminiupnpc-dev libzmq3-dev libevent-pthreads-2.0-5 -y
sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev -y
sudo apt-get install libqrencode-dev bsdmainutils -y
echo -e "${YELLOW}Packages complete...${NC}"

WANIP=$(dig +short myip.opendns.com @resolver1.opendns.com)
PASSWORD=`pwgen -1 20 -n`
if [ "x$PASSWORD" = "x" ]; then
    PASSWORD=${WANIP}-`date +%s`
fi


echo -e "${BLUE}Creating Conf File...${NC}"
sudo mkdir ~/.zelcash
sudo touch ~/.zelcash/$CONFIG_FILE
echo "rpcuser=$COIN_NAME" >> ~/.zelcash/$CONFIG_FILE
echo "rpcpassword=$PASSWORD" >> ~/.zelcash/$CONFIG_FILE
echo "rpcallowip=127.0.0.1" >> ~/.zelcash/$CONFIG_FILE
echo "rpcport=$RPCPORT" >> ~/.zelcash/$CONFIG_FILE
echo "port=$PORT" >> ~/.zelcash/$CONFIG_FILE
echo "zelnode=1" >> ~/.zelcash/$CONFIG_FILE
echo -e "${YELLOW}Enter your ZELNODE PRIVATE KEY generated by your Swing/Zelcore wallet ${NC}"
read zelnodeprivkey && echo zelnodeprivkey=$zelnodeprivkey >> ~/.zelcash/$CONFIG_FILE
echo "server=1" >> ~/.zelcash/$CONFIG_FILE
echo "daemon=1" >> ~/.zelcash/$CONFIG_FILE
echo "txindex=1" >> ~/.zelcash/$CONFIG_FILE
echo "listen=1" >> ~/.zelcash/$CONFIG_FILE
echo "logtimestamps=1" >> ~/.zelcash/$CONFIG_FILE
echo "externalip=$WANIP" >> ~/.zelcash/$CONFIG_FILE
echo "bind=$WANIP" >> ~/.zelcash/$CONFIG_FILE
echo "addnode=188.166.56.40" >> ~/.zelcash/$CONFIG_FILE
echo "addnode=165.227.163.183" >> ~/.zelcash/$CONFIG_FILE
echo "addnode=104.248.118.1" >> ~/.zelcash/$CONFIG_FILE
echo "addnode=167.99.82.56" >> ~/.zelcash/$CONFIG_FILE
echo "addnode=46.36.41.83" >> ~/.zelcash/$CONFIG_FILE
echo "addnode=165.227.156.125" >> ~/.zelcash/$CONFIG_FILE
echo "maxconnections=999" >> ~/.zelcash/$CONFIG_FILE

#begin downloading wallet
echo -e "${BLUE}Killing and removing all old instances of $COIN_NAME and Downloading new wallet...${NC}"
sudo killall $COIN_DAEMON > /dev/null 2>&1
cd /usr/local/bin && sudo rm $COIN_CLI $COIN_DAEMON > /dev/null 2>&1 && sleep 2

sudo wget -c $WALLET_DOWNLOAD -O - | sudo tar -xz
sudo chmod +x $COIN_CLI $COIN_DAEMON
sudo chmod +× /usr/local/bin/zelcash*
sudo rm -rf $WALLET_TAR_FILE
cd
#end downloading/cleaning up wallet

echo -e "${BLUE}Downloading chain params...${NC}"
wget $FETCHPARAMS
sudo chmod +x fetch-params.sh
sudo bash fetch-params.sh
sudo chown -R $USERNAME:$USERNAME /home/$USERNAME
echo -e "${YELLOW}Done fetching chain params${NC}"

echo -e "${BLUE}Creating system service file....${NC}"
 cat << EOF > /etc/systemd/system/$COIN_NAME.service
[Unit]
Description=$COIN_NAME service
After=network.target
[Service]
User=$USERNAME
Group=$USERNAME
Type=forking
#PIDFile=~/.zelcash/$COIN_NAME.pid
ExecStart=$COIN_PATH/$COIN_DAEMON -daemon -conf=~/.zelcash/$CONFIG_FILE -datadir=~/.zelcash/
ExecStop=-$COIN_PATH/$COIN_CLI -conf=~/.zelcash/$CONFIG_FILE -datadir=~/.zelcash stop
Restart=always
Restartsec=5
PrivateTmp=true
TimeoutStopSec=60s
TimeoutStartSec=5s
StartLimitInterval=120s
StartLimitBurst=15
[Install]
WantedBy=multi-user.target
EOF

sudo chmod 755 /etc/systemd/system/$COIN_NAME.service
sudo systemctl daemon-reload
sleep 3
sudo systemctl start $COIN_NAME.service
sudo systemctl enable $COIN_NAME.service >/dev/null 2>&1

echo -e "${YELLOW}Systemctl Complete....${NC}"

echo "If you see *error* message, do not worry we are killing wallet again to make sure its dead"
echo ""
echo -e "{YELLOW}=================================================================="
echo "DO NOT CLOSE THIS WINDOW OR TRY TO FINISH THIS PROCESS "
echo "PLEASE WAIT 2 MINUTES UNTIL YOU SEE THE RELOADING WALLET MESSAGE"
echo -e "==================================================================${NC}"
echo ""

echo -e "${BLUE}Configuring firewall and enabling fail2ban...${NC}"
#add a firewall
sudo ufw allow ssh/tcp
sudo ufw allow $PORT/tcp
sudo ufw allow $RPCPORT/tcp
sudo ufw logging on
sudo ufw default deny incoming
sudo ufw default allow outgoing
echo "y" | sudo ufw enable >/dev/null 2>&1
sudo systemctl enable fail2ban >/dev/null 2>&1
sudo systemctl start fail2ban >/dev/null 2>&1
echo -e "${YELLOW}Basic security completed...${NC}"

echo -e "${BLUE}Restarting $COIN_NAME wallet with new configs, 30 seconds...${NC}"
$COIN_DAEMON -daemon
sleep 30

echo -e "${BLUE}Getting info...${NC}"
$COIN_CLI getinfo

echo -e "${BLUE}Starting your ZELNODE with final details${NC}"

sleep 10

printf "${PURPLE}"
figlet -t -k "WELCOME   TO   ZELNODES" 
printf "${STOP}"

echo "============================================================================="
echo -e "${CYAN}THE FOLLOWING LINE IS YOUR ZELNODE LINE FOR YOUR ZELNODE CONF FILE ${NC}"
echo -e "ZN1 ${YELLOW}$WANIP:$PORT ${BLUE}$zelnodeprivkey ${NC}TxID OUTPUT"
echo -e "COURTESY OF ${GREEN}ALTTANK FAM ${NC}AND ${GREEN}DK808 ${NC}"
echo "============================================================================="
sleep 1
